embed_assets: on
javascript_compressor: yui

javascripts:
  common:
    - public/javascripts/jquery-1.5.2.js
    - public/javascripts/jquery-ui-1.8.11.custom/js/jquery-ui-1.8.11.custom.min.js
    - public/javascripts/jquery.hoverIntent.js
    - public/javascripts/jquery.ui.totop.js
    - public/javascripts/jquery-ujs/rails.js
    - public/javascripts/jquery.jnotify.js
    - public/javascripts/jquery.ui.selectmenu.js    
    - public/javascripts/katello.js
    - public/javascripts/application.js
    - public/javascripts/jquery.linkHover.js    
    - public/javascripts/jquery.sparkline.min.js    
  html5:
    - public/javascripts/html5.js
  dashboard:
    - public/javascripts/headpin.sparkline.js   
  content:
    - public/javascripts/content.js
    - public/javascripts/jquery.periodicalupdater.js
  katello_client:
    - public/javascripts/katello_client.js
  environment:
    - public/javascripts/environment.js
  changeset:
    - public/javascripts/changeset.js
  systems:
    - public/javascripts/systems.js
  form:
    - public/javascripts/jquery.form.js
  treetable:
    - public/javascripts/jquery.treeTable.js
  panel:
    - public/javascripts/jquery.ba-resize.js
    - public/javascripts/panel.js
  provider:
    - public/javascripts/provider.js
  notices:
    - public/javascripts/notices.js
    - public/javascripts/jquery.periodicalupdater.js
  password:
    - public/javascripts/jquery.simplePassMeter.js
  user:
    - public/javascripts/user.js
  user_edit:
    - public/javascripts/user_edit.js
  org_edit:
    - public/javascripts/org_edit.js
  activation_key:
    - public/javascripts/activation_key.js
  subscription:
    - public/javascripts/subscription.js
    - public/javascripts/headpin.sparkline.js          
  role:
    - public/javascripts/role.js
  role_edit:
    - public/javascripts/role_edit.js
  edit:
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/jquery.jeditable.ajaxupload.js
    - public/javascripts/jquery.ajaxfileupload.js
    - public/javascripts/jeditable_helpers.js
  multiselect:
    - public/javascripts/jquery.ui.multiselect.js
  fancyqueries:
    - public/javascripts/jquery.fancyqueries.js
    - public/javascripts/search.js
  bbq:
    - public/javascripts/jquery.ba-bbq.js
        
stylesheets:
  common:
    - public/javascripts/jquery-ui-1.8.11.custom/css/custom-theme/jquery-ui-1.8.11.custom.css
    - public/stylesheets/compiled/screen.css
    - public/stylesheets/compiled/katello.css
    - public/stylesheets/compiled/headpin.css    
    - public/stylesheets/jquery.loadmask.css
    - public/stylesheets/compiled/ie.css
    - public/stylesheets/jquery.jnotify.css
    - public/stylesheets/jquery.treeTable.css
  fancyqueries:
    - public/stylesheets/compiled/fancyqueries.css
  loginpage:
    - public/stylesheets/compiled/loginpage.css
  dashboard:
    - public/stylesheets/compiled/dashboard.css
  current:
  imports:
  systems:
  activation_keys:
  generic:
  empty:
